spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gms_database}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

jwt:
  secret-key: ${JWT_SECRET_KEY:c1e1ef088b9caba156454117f589f9abb1799805f9d26c766a570376d127cc4b}
  expiration: 3600000
  expiration-refresh: 86400000

server:
  port: ${PORT:8080}